# .gitlab-ci.yml
#
# ink-waterfall
#
# pipelines can be triggered manually in the web

stages:
  - test

variables:
  GIT_STRATEGY:                    fetch
  GIT_DEPTH:                       "100"
  CARGO_HOME:                      "/ci-cache/${CI_PROJECT_NAME}/cargo/${CI_COMMIT_REF_NAME}/${CI_JOB_NAME}"
  CARGO_TARGET_DIR:                "/ci-cache/${CI_PROJECT_NAME}/targets/${CI_COMMIT_REF_NAME}/${CI_JOB_NAME}"
  RUST_LIB_BACKTRACE:              "0"
  CI_IMAGE:                        "paritytech/ink-waterfall-ci:latest"
  RUST_LOG:                        "info"
  RUST_TEST_THREADS:               "1"
  WATERFALL_TIMEOUT_SECS_PER_TEST: "600"

workflow:
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH

.collect-artifacts:                &collect-artifacts
  artifacts:
    name:                          "${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
    when:                          on_success
    expire_in:                     7 days
    paths:
      - artifacts/

.docker-env:                       &docker-env
  image:                           "${CI_IMAGE}"
  before_script:
    - cargo -vV
    - rustc -vV
    - rustup show
    - bash --version
    - ./.scripts/pre_cache.sh
    - sccache -s
    - git show
  rules:
    - if: $CI_PIPELINE_SOURCE == "web"
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_COMMIT_REF_NAME == "master"
    - if: $CI_COMMIT_REF_NAME == "tags"
    - if: $CI_COMMIT_REF_NAME =~ /^[0-9]+$/                   # PRs
    - if: $CI_COMMIT_REF_NAME =~ /^v[0-9]+\.[0-9]+.*$/        # i.e. v1.0, v2.1rc1
  dependencies:                    []
  interruptible:                   true
  retry:
    max:                           2
    when:
      - runner_system_failure
      - unknown_failure
      - api_failure
  tags:
    - linux-docker


test-with-master-canvas-ui:
  stage:                           test
  <<:                              *docker-env
  before_script:
    # Install the latest HEAD of canvas-ui master here.
    # We don't do this in the Dockerfile, since caching might interfere and
    # we might not always have the latest master here.
    - git clone --depth 1 https://github.com/paritytech/canvas-ui.git

    - cd canvas-ui
    - yarn install
    - yarn start > /tmp/canvas-ui.log 2>&1 &
    - cd ..

    # Loop until Canvas UI is ready
    - until $(curl --output /dev/null --silent --head --fail http://localhost:3000); do
        printf '.';
        sleep 1;
      done

    - canvas --tmp --dev > /tmp/canvas.log 2>&1 &

    - git clone --depth 1 https://github.com/paritytech/ink.git
  variables:
    INK_EXAMPLES_PATH:                "./ink/examples/"
    CANVAS_UI_URL:                    "http://localhost:3000"
  script:
    - cargo test --features headless -- --nocapture
  after_script:
    - pkill -f canvas

test-with-published-canvas-ui:
  stage:                           test
  <<:                              *docker-env
  before_script:
    - canvas --tmp --dev > /tmp/canvas.log 2>&1 &
    - git clone --depth 1 https://github.com/paritytech/ink.git
  variables:
    INK_EXAMPLES_PATH:                "./ink/examples/"

    # run the tests with the published `canvas-ui` (at the `gh-pages` branch)
    CANVAS_UI_URL:                    "https://paritytech.github.io/canvas-ui/"
  script:
    - cargo test --features headless
  after_script:
    - pkill -f -x "canvas --tmp --dev"