[package]
name = "waterfall"
version = "0.1.0"
authors = ["Michael Mueller <mich@elmueller.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures-core = "0.3.0"
futures-util = "0.3.0"
tokio = { version = "1", features = [ "full" ] }
webdriver = { version = "0.43.0", default-features = false }
fantoccini = { version = "0.17.3" }
serde = "1.0"
serde_json = "1.0"
